theme: jekyll-theme-minimal
title: Liberal Tomorrow
description: Political action today for a liberal tomorrow
logo: LT.jpg
twitter: https://twitter.com/LiberalTomorrow
google_analytics: UA-163820281-1

plugins:
    - jekyll-seo-tag
